server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bcnl4?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        highlight_sql: true

knife4j:
  # 是否启用Knife4j功能
  enable: true
  # Basic认证配置
  basic:
    # 是否启用Basic认证
    enable: true
    # 认证用户名
    username: admin
    # 认证密码
    password: 123456
  # 界面设置配置
  setting:
    # 界面语言设置为中文
    language: zh_cn
